using Microsoft.EntityFrameworkCore;
using TinyUrl.Core;

namespace TinyUrl.Core.Tests;

public class ShortenUrlUseCaseTests : IDisposable
{
    private readonly AppDbContext _context;
    private readonly ShortenUrlUseCase _useCase;

    public ShortenUrlUseCaseTests()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;

        _context = new AppDbContext(options);
        _context.Database.OpenConnection();
        _context.Database.EnsureCreated();

        var repository = new UrlRepository(_context);
        var slugGenerator = new SlugGenerator();
        _useCase = new ShortenUrlUseCase(repository, slugGenerator);
    }

    public void Dispose()
    {
        _context.Database.CloseConnection();
        _context.Dispose();
    }

    [Fact]
    public async Task ShortenAsync_WithValidOriginalUrl_CreatesRecordWithAutoGeneratedSlug()
    {
        var result = await _useCase.ShortenAsync("https://example.com/some-long-path", baseUrl: "https://short.url");

        Assert.NotNull(result);
        Assert.NotEmpty(result.Slug);
        Assert.Equal(7, result.Slug.Length);
        Assert.Equal("https://short.url/" + result.Slug, result.ShortUrl);

        var stored = await _context.ShortUrls.FirstOrDefaultAsync(s => s.Slug == result.Slug);
        Assert.NotNull(stored);
        Assert.Equal("https://example.com/some-long-path", stored.OriginalUrl);
        Assert.Equal(0, stored.ClickCount);
        Assert.Null(stored.ExpiresAt);
    }

    [Fact]
    public async Task ShortenAsync_WithCustomSlug_StoresSlugVerbatim()
    {
        var result = await _useCase.ShortenAsync("https://example.com/page", baseUrl: "https://short.url", customSlug: "my-brand");

        Assert.Equal("my-brand", result.Slug);
        Assert.Equal("https://short.url/my-brand", result.ShortUrl);

        var stored = await _context.ShortUrls.FirstOrDefaultAsync(s => s.Slug == "my-brand");
        Assert.NotNull(stored);
        Assert.Equal("https://example.com/page", stored.OriginalUrl);
    }

    [Fact]
    public async Task ShortenAsync_WithExpiresAt_PersistsExpiration()
    {
        var expiresAt = new DateTime(2026, 6, 30, 12, 0, 0, DateTimeKind.Utc);

        var result = await _useCase.ShortenAsync("https://example.com", baseUrl: "https://short.url", expiresAt: expiresAt);

        var stored = await _context.ShortUrls.FirstOrDefaultAsync(s => s.Slug == result.Slug);
        Assert.NotNull(stored);
        Assert.Equal(expiresAt, stored.ExpiresAt);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("not-a-url")]
    [InlineData("ftp://invalid-scheme.com")]
    public async Task ShortenAsync_WithInvalidOriginalUrl_ThrowsArgumentException(string invalidUrl)
    {
        await Assert.ThrowsAsync<ArgumentException>(() =>
            _useCase.ShortenAsync(invalidUrl, baseUrl: "https://short.url"));
    }

    [Fact]
    public async Task ShortenAsync_WithConflictingCustomSlug_ThrowsInvalidOperationException()
    {
        await _useCase.ShortenAsync("https://example.com/first", baseUrl: "https://short.url", customSlug: "taken");

        await Assert.ThrowsAsync<InvalidOperationException>(() =>
            _useCase.ShortenAsync("https://example.com/second", baseUrl: "https://short.url", customSlug: "taken"));
    }
}
